version: '3'
services:
  zookeeper:
    container_name: zookeeper
    network_mode: host
    image: confluentinc/cp-zookeeper:4.1.0
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:4.1.0
    network_mode: host
    ports:
      - 9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  kafka-connect-rest:
    container_name: kafka-rest
    network_mode: host
    image: docker.io/confluentinc/cp-kafka-rest
    ports:
      - 8082
    environment:
      - BOOTSTRAP_SERVER=localhost:9092
      - ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_REST_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_REST_HOST_NAME=localhost
      - ADVERTISED_HOST_NAME=PLAINTEXT://localhost:8082
      - CONNECT_LOG4J_ROOT_LOGLEVEL=DEBUG
    depends_on:
      - zookeeper

