version: '3'

services:
  monitoror:
    image: ntkzwane/monitoror:arm
    container_name: monitoror
    environment:
      MO_CONFIG: /data/config.json
    volumes:
      - $MO_CONFIG:/data
    restart: unless-stopped
    network_mode: host

